### ISSUE TITLE
.titlebar CSS class causes black titlebar under Gnome

### ISSUE THREAD

**Issue by Alexander-Wilms** [dahenson/agenda#43] opened 2017-06-21 02:21 UTC
Not sure if this is a bug in Adwaita or Agenda or elsewhere, but this patch fixes it. Maybe you could apply different styles depending on whether Agenda is run on elementary or not, like Vocal: https://github.com/needle-and-thread/vocal/blob/master/src/MainWindow.vala#L248

```
--- ./src/AgendaWindow.vala
+++ ./src/AgendaWindow.vala
@@ -56,8 +56,6 @@
 
             const string ELEMENTARY_STYLESHEET = """
                 .titlebar {
-                    background-color: @bg_color;
-                    background-image: none;
                     border: none;
                 }
```

**Comment by dahenson** [comment] 2017-06-21 13:38
I'm not a huge fan of including cross-platform fixes, when Agenda was purely designed to be run on elementary OS. These two lines are not a bug, they are an intentional design decision to make the GUI look the best on elementary OS. For now, I'm going to mark this as won't fix until I have a better solution for porting to other themes without breaking the elementary OS experience.

**Closed by dahenson** 2017-06-21 13:38 UTC
Labels: wontfix

**Comment by Alexander-Wilms** [comment] 2017-06-21 14:54
Maybe it's a bug in Adwaita since you use the same  @bg_color in other classes and they don't appear black.
